In [56]:
import pandas as pd
import numpy as np
import altair as alt

In [2]:
snp=pd.read_csv('../data/sampled_data.csv')

In [6]:
snp.head()

,Name,Gender,Allele1,Allele2,Population
0,P11980,F,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCGCTGATTCCCGTG...,CTCCGTCGACGCTTTAGGGACATGGATGGGAGCTCTGATTCCCGTG...,EthP
1,P638,F,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGACTCCTGTG...,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTTCCGTG...,EthP
2,P5939,M,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCCGATTCCCGTG...,CTCCGTCGAAGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,EthP
3,P6402,M,CTCCGTCGACGCTTTAGGGACATAGATGGAAGCTCTGATTCCCGTG...,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,EthP
4,P3888,F,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,EthP

In [4]:
Allele_1 = list(snp.Allele1)
Allele_2 = list(snp.Allele2)

In [51]:
def most_frequent(Allele):
    Most_Frequent=[]
    for j in range(len(Allele[0])):
        List=[]
        
        for i in range(len(Allele)):
            List.append(Allele[i][j])
            
        Most_Frequent.append(max(set(List), key=List.count))
    return Most_Frequent

In [52]:
Most_Frequent = most_frequent(Allele_1)

In [19]:
# It takes about 8-10 minutes
def combination(x, Most_Frequent):
    List=[]
    for i in range (len(x.Allele1)):
        if x.Allele1[i]!=x.Allele2[i]:
            List.append(1)
        elif x.Allele1[i]==Most_Frequent[i]:
            List.append(0)
        else:
            List.append(2)
    return List

In [20]:
combinated = snp.apply(lambda x: combination(x, Most_Frequent), axis=1)

In [36]:
combinated = combinated.rename('combinated')

In [40]:
expanded = combinated.apply(pd.Series)

In [42]:
expanded = expanded.rename(columns = lambda x : 'r' + str(x))

In [47]:
snp=snp.join(expanded)

In [54]:
snp.to_csv('Processed_data.csv')

In [55]:
snp.head()

,Name,Gender,Allele1,Allele2,Population,r0,r1,r2,r3,r4,...,r39098,r39099,r39100,r39101,r39102,r39103,r39104,r39105,r39106,r39107
0,P11980,F,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCGCTGATTCCCGTG...,CTCCGTCGACGCTTTAGGGACATGGATGGGAGCTCTGATTCCCGTG...,EthP,0,0,0,0,0,...,1,1,2,0,1,2,2,2,2,0
1,P638,F,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGACTCCTGTG...,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTTCCGTG...,EthP,0,0,0,0,0,...,1,2,1,1,0,1,1,2,1,2
2,P5939,M,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCCGATTCCCGTG...,CTCCGTCGAAGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,EthP,0,0,0,0,0,...,1,0,1,0,0,1,0,2,2,1
3,P6402,M,CTCCGTCGACGCTTTAGGGACATAGATGGAAGCTCTGATTCCCGTG...,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,EthP,0,0,0,0,0,...,1,1,1,0,2,1,1,2,1,2
4,P3888,F,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,CTCCGTCGACGCTTTAGGGACATAGATGGGAGCTCTGATTCCCGTG...,EthP,0,0,0,0,0,...,1,2,1,1,2,2,2,1,0,1